# Create the action definition using repo.js

name: 'tdupoiron - Create a repository'

description: 'Create a repository'

inputs:

  repo_name:
    description: The name of the repository
    required: true
  repo_is_private:
    description: The visibility of the repository
    required: false
    default: public

outputs:
  repo_id:
    description: The ID of the repository
  repo_full_name:
    description: The full name of the repository

runs:
  using: "node16"
  main: "dist/action.js"