name: Extract repository settings from Issue

on:
  workflow_call:
    inputs:
      issue_body:
        description: The body of the issue
        type: string
        required: true
    
    outputs:
      repository_name:
        description: The name of the repository
        value: ${{ jobs.extract_repository_settings.outputs.repository_name }}
      repository_visibility:
        description: The visibility of the repository
        value: ${{ jobs.extract_repository_settings.outputs.repository_visibility }}

jobs:

  extract_repository_settings:

    runs-on: ubuntu-latest
    outputs: 
      repository_name: ${{ steps.extract.outputs.repository_name }}
      repository_visibility: ${{ steps.extract.outputs.repository_visibility }}

    steps:
      - name: Extract repository settings
        id: extract
        run: |
          echo "${{ inputs.issue_body }}" > body.txt
          echo "::set-output name=repository_name::$(awk '/### Repository name/{getline; getline; print}' body.txt)"
          echo "::set-output name=repository_visibility::$(awk '/### Repository visibility/{getline; getline; print}' body.txt)"