name: Create Repository on Issue creation via inline scripts

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:

  # 1. Extract repository settings from issue body
  extract_repository_settings:

    if: contains(github.event.issue.labels.*.name, 'repo-ops')

    uses: ./.github/workflows/rwf-extract-repository-settings.yml
    with: 
      issue_body: ${{ github.event.issue.body }}
