name: Create Repository on Issue creation

on:
  issues:
    types:
      - opened
      - reopened
      - edited

env:
  #LABEL_NEW_REQUEST: "0 - new request"
  #LABEL_CREATING_REPO: "1 - creating repository"
  #LABEL_REPO_CREATED: "2 - repository created"
  #LABEL_ERROR: "3 - error"

jobs:

  # Extract repository settings from issue body
  extract_repository_settings:
    if: contains(github.event.issue.labels.*.name, 'repo-ops')

    runs-on: ubuntu-latest
    outputs: 
      repository_name: ${{ steps.extract.outputs.repository_name }}
      repository_visibility: ${{ steps.extract.outputs.repository_visibility }}

    steps:
      - name: Extract repository settings
        id: extract
        run: |
          echo "${{ github.event.issue.body }}" >> body.txt
          echo "::set-output name=repository_name::$(awk '/### Repository name/{getline; getline; print}' body.txt)"
          echo "::set-output name=repository_visibility::$(awk '/### Repository visibility/{getline; getline; print}' body.txt)"

  # Request approval
  request_approval:
    runs-on: ubuntu-latest
    needs: extract_repository_settings

    steps:

      - name: Rename issue
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "New repository request: ${{ needs.extract_repository_settings.outputs.repository_name }}"
            })

      - name: Add label ${{ env.LABEL_CREATING_REPO }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: ${{ env.LABEL_CREATING_REPO }}
          remove-labels: ${{ env.LABEL_NEW_REPO }}